/**
 * envcheck init — build a schema (.env.example) from the keys already present
 * in discovered .env* files. Never copies secret values; only key names + blank
 * values, preserving any preceding comments when a single source file is used.
 */
import { existsSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { scanEnvFiles } from "./scan.ts";
import { loadEnvFile } from "./load.ts";
import { writeAtomic } from "./atomic.ts";
import { loadConfig } from "./config.ts";
import { EnvcheckError } from "./errors.ts";
import { Exit } from "./exit.ts";
import { c } from "./color.ts";

export interface InitFlags {
  cwd: string;
  schema?: string;
  ignore: string[];
  force: boolean;
}

export interface InitOutcome {
  exitCode: number;
  text: string;
}

export function runInit(flags: InitFlags): InitOutcome {
  const root = resolve(flags.cwd);
  const config = loadConfig(root);
  const ignore = [...config.ignore, ...flags.ignore];
  const outName = flags.schema ?? config.schema ?? ".env.example";
  const outAbs = join(root, outName);

  if (existsSync(outAbs) && !flags.force) {
    throw new EnvcheckError(
      Exit.Usage,
      `${outName} already exists.`,
      "Refusing to overwrite a schema without --force.",
      `envcheck init --force   # or pass --schema <other-name>`,
    );
  }

  const found = scanEnvFiles({ root, extraIgnore: ignore });
  const sources = found.filter((f) => {
    const base = f.rel.split("/").pop() ?? f.rel;
    return base !== outName && !base.endsWith(".example") && !base.endsWith(".sample") && !base.endsWith(".template");
  });

  if (sources.length === 0) {
    throw new EnvcheckError(
      Exit.NotFound,
      "No .env files found to seed a schema from.",
      `Scanned ${root} and only saw schema-like names, or nothing at all.`,
      "Create a .env with your keys first, then re-run: envcheck init",
    );
  }

  const keyOrder: string[] = [];
  const seen = new Set<string>();
  const comments = new Map<string, string>();

  for (const f of sources) {
    const loaded = loadEnvFile(f.abs, f.rel);
    for (const entry of loaded.parsed.entries) {
      if (!seen.has(entry.key)) {
        seen.add(entry.key);
        keyOrder.push(entry.key);
      }
      if (entry.comment && !comments.has(entry.key)) {
        comments.set(entry.key, entry.comment);
      }
    }
  }

  if (keyOrder.length === 0) {
    throw new EnvcheckError(
      Exit.NotFound,
      "Found .env files but no keys inside them.",
      "Every candidate file was empty or comment-only.",
      "Add KEY=value lines to a .env, then: envcheck init",
    );
  }

  keyOrder.sort((a, b) => a.localeCompare(b));

  const lines: string[] = [
    `# Generated by envcheck init — fill in real values in your .env files.`,
    `# Schema keys (${keyOrder.length}) collected from: ${sources.map((s) => s.rel).join(", ")}`,
    "",
  ];
  for (const key of keyOrder) {
    const comment = comments.get(key);
    if (comment) lines.push(`# ${comment}`);
    lines.push(`${key}=`);
  }
  lines.push("");

  writeAtomic(outAbs, lines.join("\n"), undefined);

  const text = [
    `${c.green("wrote")} ${outName}  ${c.dim(`${keyOrder.length} keys from ${sources.length} file${sources.length === 1 ? "" : "s"}`)}`,
    c.dim("next: edit values in your .env, then envcheck check"),
    "",
  ].join("\n");

  return { exitCode: Exit.Ok, text };
}
